config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('users/', include("django.contrib.auth.urls")),
]

favorites/urls.py
from django.urls import path

from .views import SaveFavoriteView

app_name = "favorites"

urlpatterns = [path('save/', SaveFavoriteView.as_view(), name="save")]

pages/urls.py
from favorites.urls import urlpatterns
from django.urls import path

from .views import HomeView

app_name = 'pages'

urlpatterns = [path('', HomeView.as_view(), name='home')]

favorites/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Favorite(models.Model):
    item = models.ForeignKey("items.Item", on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        unique_together = (('item', 'user'),)

    def __str__(self):
        return f"{self.item.name} ({self.user.username})"

items/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField("item name", max_length=100)

    def __str__(self):
        return self.name

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

favorites/forms.py
from django import forms

from items.models import Item
from .models import Favorite


class SaveFavoriteForm(forms.Form):
    item = forms.IntegerField(widget=forms.HiddenInput(), required=True)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(request.POST, *args, **kwargs)

    def clean_item(self):
        item = self.cleaned_data.get('item')
        try:
            item = Item.objects.get(pk=item)
        except Item.DoesNotExist:
            raise forms.ValidationError(
                "The item you want to save does not exist"
            )
        return item

    def save(self, commit=True):
        item = self.cleaned_data.get("item")
        try:
            favorite = Favorite.objects.get(user=self.request.user, item=item)
        except Favorite.DoesNotExist:
            favorite = Favorite(user=self.request.user, item=item)
            if commit:
                favorite.save()
        return favorite

favorites/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect

from favoritecart.helpers import redirect_to_login
from favoritecart.cart import FavoriteCart
from .forms import SaveFavoriteForm


class SaveFavoriteView(View):
    """View responsible to handle the Favorite saving process."""

    def post(self, request):
        form = SaveFavoriteForm(request)
        if form.is_valid():
            return self.form_valid(form)

    def form_valid(self, form):
        item = form.cleaned_data['item']
        print("Authenticated? ", self.request.user)
        if not self.request.user.is_authenticated:
            cart = FavoriteCart(self.request)
            cart.add({"item": item.id, "user": "user"})
            return redirect_to_login(self.request)
        form.save(self.request)
        return redirect("pages:home")

items/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render
from django.views.generic import ListView

from items.models import Item


class HomeView(ListView):
    model = Item
    template_name = 'pages/home.html'

users/views.py
from django.shortcuts import render

# Create your views here.

pages/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<ul>
{% for item in  object_list %}
    <li>
        {{ item.name }}
        <form class="save-form" action="{% url 'favorites:save' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name='item' value="{{ item.id }}">
            <button class="save-form__button" type="submit">Sauvegarder</button>
        </form>
    </li>
{% endfor %}
</ul>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% block head_scripts %}
    {% endblock head_scripts %}

    {% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock styles %}
</head>
<body>
    {% block content %}
    {% endblock content %}

    {% block bottom_scripts %}
    {% endblock bottom_scripts %}
</body>
</html>